language: ruby
rvm:
  - 2.3.1
before_install:
  - nvm install 6.2.0
install:
  - bundle install --jobs=3 --retry=3
  - npm install
before_script:
  - bundle exec rake db:test:prepare
script:
  - bundle exec rake health
