# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0feb9ad04e4f1070d8ccd05fbd970a4e33c3598eb033693c266a36dc3b272f23252040604f49879d78530725eac1f967fc220b62202d67828bf9c224dd09640f

test:
  secret_key_base: 2f2e19d3302433da7ee4566f20c2dd98098411f9b89a70d6d71f986d73be33069a74ee42b4c60029ee91e43479ac1bddca58be7d91196aa4650b2932d12b4eef

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
